name: Move assigned issues

on:
  issues:
    types: [assigned]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: write
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: write
  security-events: read
  statuses: read


jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: ${{ vars.PROJECT_NAME }} 
          column: ${{ vars.ASSIGNED_STATUS }}
          repo-token: ${{ secrets.GH_TOKEN }}
